<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Feedback Dashboard</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css" rel="stylesheet">
    <style>
        :root{--ink:#172033;--muted:#718096;--brand:#5b5bd6;--line:#e7eaf0;--canvas:#f5f7fb;--green:#139c6d}*{box-sizing:border-box}body{margin:0;background:var(--canvas);color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}.topbar{background:#fff;border-bottom:1px solid var(--line);position:sticky;top:0;z-index:1020}.brand-mark{width:42px;height:42px;border-radius:13px;background:linear-gradient(135deg,var(--brand),#8b5cf6);display:grid;place-items:center;color:#fff;box-shadow:0 8px 18px #5b5bd633}.page-shell{max-width:1500px;margin:auto;padding:30px 24px 50px}.eyebrow{color:var(--brand);font-size:.75rem;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.page-title{font-weight:760;letter-spacing:-.04em}.soft-btn{border:1px solid var(--line);background:#fff;color:var(--ink);border-radius:12px;padding:.65rem .95rem;font-weight:650;text-decoration:none}.soft-btn:hover{color:var(--brand);border-color:#bdbdf0}
        .stat-card{height:100%;background:#fff;border:1px solid var(--line);border-radius:17px;padding:19px;box-shadow:0 8px 28px rgba(32,41,64,.045);transition:.2s}.stat-card:hover{transform:translateY(-2px)}.stat-icon{width:42px;height:42px;border-radius:12px;display:grid;place-items:center}.stat-label{color:var(--muted);font-size:.77rem;font-weight:700}.stat-value{font-size:1.65rem;font-weight:780;letter-spacing:-.04em;margin-top:7px}.panel{background:#fff;border:1px solid var(--line);border-radius:20px;box-shadow:0 10px 35px rgba(32,41,64,.055);overflow:hidden}.toolbar{padding:20px;border-bottom:1px solid var(--line)}.search-box{position:relative}.search-box i{position:absolute;left:14px;top:50%;transform:translateY(-50%);color:#9aa3b2}.search-box input{padding-left:41px}.form-control,.form-select{border-color:var(--line);border-radius:11px;min-height:43px}.form-control:focus,.form-select:focus{border-color:#aaaaf1;box-shadow:0 0 0 .22rem #5b5bd615}
        .table{margin:0;min-width:1050px}.table thead th{padding:14px 17px;background:#fafbfc;border-bottom:1px solid var(--line);color:#697386;font-size:.69rem;letter-spacing:.07em;text-transform:uppercase;white-space:nowrap}.table tbody td{padding:15px 17px;border-color:#eff1f5;vertical-align:middle}.table tbody tr:hover{background:#fafaff}.person{display:flex;align-items:center;gap:11px}.avatar{width:38px;height:38px;border-radius:12px;background:#ededff;color:var(--brand);display:grid;place-items:center;font-weight:800}.person-name{font-weight:700}.subtext{font-size:.77rem;color:var(--muted)}.rating{display:inline-flex;align-items:center;gap:5px;padding:6px 10px;border-radius:999px;font-size:.74rem;font-weight:720;white-space:nowrap}.great{background:#e8f8f1;color:#087d55}.good{background:#e8f4ff;color:#1569ae}.fair{background:#fff5dc;color:#9d6500}.poor{background:#ffebee;color:#bd3341}.action-btn{border:1px solid var(--line);background:#fff;width:36px;height:36px;border-radius:10px;color:#616b7d}.action-btn:hover{border-color:#b9b9ec;color:var(--brand);background:#f6f6ff}.table-zone{position:relative;min-height:250px}.loading-layer{position:absolute;inset:0;background:#ffffffc7;backdrop-filter:blur(1px);display:none;place-items:center;z-index:5}.pagination-wrap{padding:17px 20px;border-top:1px solid var(--line)}.page-link{border:0;border-radius:9px!important;margin:0 2px;color:#596274}.page-item.active .page-link{background:var(--brand)}.empty{padding:64px 20px;text-align:center;color:var(--muted)}.modal-content{border:0;border-radius:20px;box-shadow:0 30px 80px #17203333}.modal-header,.modal-footer{border-color:var(--line)}.details-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 28px}.detail{padding:11px 0;border-bottom:1px solid var(--line)}.detail label{display:block;color:var(--muted);font-size:.7rem;font-weight:750;letter-spacing:.05em;text-transform:uppercase;margin-bottom:4px}.long-answer{background:#f8f9fc;border:1px solid var(--line);border-radius:13px;padding:14px;margin-top:13px}.long-answer label{color:var(--brand);font-size:.71rem;font-weight:780;text-transform:uppercase}.long-answer p{margin:7px 0 0;white-space:pre-wrap}@media(max-width:767px){.page-shell{padding:20px 12px}.details-grid{grid-template-columns:1fr}.toolbar{padding:15px}.top-label{display:none}}
    </style>
</head>
<body>
<header class="topbar"><div class="container-fluid px-3 px-md-4 py-3 d-flex align-items-center justify-content-between"><div class="d-flex align-items-center gap-3"><div class="brand-mark"><i class="bi bi-chat-heart-fill"></i></div><div><div class="fw-bold">SPC Feedback</div><div class="subtext">Attendee experience</div></div></div><div class="d-flex gap-2"><a href="{{ route('dashboard') }}" class="soft-btn"><i class="bi bi-grid me-md-2"></i><span class="top-label">Dashboard</span></a><a href="{{ route('analytics') }}" class="soft-btn"><i class="bi bi-bar-chart-line me-md-2"></i><span class="top-label">Analytics</span></a></div></div></header>
<main class="page-shell">
    <div class="d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3 mb-4"><div><div class="eyebrow mb-2">Conference insights</div><h1 class="page-title h2 mb-1">Attendee feedback</h1><p class="text-secondary mb-0">Understand what attendees loved and where the experience can improve.</p></div><button id="exportBtn" class="btn btn-dark rounded-3 px-3 py-2"><i class="bi bi-download me-2"></i>Export current results</button></div>
    @php $cards=[['total','Total feedback','chat-left-text','#eeedff','#514bc4'],['excellent','Excellent rating','star-fill','#e8f8f1','#087d55'],['high_impact','High spiritual impact','heart-fill','#fff2df','#b16d00'],['attend_again','Will attend again','arrow-repeat','#e8f4ff','#1675d1'],['inspiring','Inspiring speakers','mic-fill','#ffebf5','#c43577'],['exceptional','Exceptional content','book-fill','#f2eaff','#7b3fc2']]; @endphp
    <div class="row g-3 mb-4">@foreach($cards as [$key,$label,$icon,$bg,$color])<div class="col-6 col-md-4 col-xl-2"><div class="stat-card"><div class="d-flex justify-content-between"><div class="stat-label">{{ $label }}</div><div class="stat-icon" style="background:{{ $bg }};color:{{ $color }}"><i class="bi bi-{{ $icon }}"></i></div></div><div class="stat-value" data-stat="{{ $key }}">{{ number_format($stats[$key]) }}</div></div></div>@endforeach</div>
    <section class="panel"><div class="toolbar"><div class="row g-2 align-items-center"><div class="col-12 col-lg-7"><div class="search-box"><i class="bi bi-search"></i><input id="searchInput" class="form-control" value="{{ request('search') }}" placeholder="Search name, email, response or testimony"></div></div><div class="col-7 col-lg-3"><select id="ratingFilter" class="form-select"><option value="">All overall ratings</option>@foreach(['Excellent','Very Good','Good','Fair','Poor'] as $rating)<option value="{{ $rating }}" @selected(request('rating')===$rating)>{{ $rating }}</option>@endforeach</select></div><div class="col-5 col-lg-2 text-end"><span class="subtext" id="resultSummary">Loading…</span></div></div></div>
        <div class="table-zone"><div class="loading-layer" id="loading"><div class="spinner-border text-primary"></div></div><div class="table-responsive"><table class="table"><thead><tr><th>Attendee</th><th>Overall</th><th>Spiritual impact</th><th>Content</th><th>Speakers</th><th>Attend again</th><th class="text-end">Action</th></tr></thead><tbody id="tableBody"></tbody></table></div></div>
        <div class="pagination-wrap d-flex flex-column flex-sm-row justify-content-between align-items-center gap-2"><div class="subtext" id="rangeText"></div><nav><ul class="pagination pagination-sm mb-0" id="pagination"></ul></nav></div></section>
</main>
<div class="modal fade" id="detailsModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header px-4"><div><div class="eyebrow">Attendee response</div><h5 class="modal-title mt-1">Feedback details</h5></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body px-4" id="modalBody"></div><div class="modal-footer px-4"><button class="btn btn-light" data-bs-dismiss="modal">Close</button></div></div></div></div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
const feedbackUrl=@json(route('get.feedback'));let pageData=@json($registrations),requestController;
const escapeHtml=value=>{const el=document.createElement('div');el.textContent=value??'';return el.innerHTML};const display=value=>escapeHtml(value||'N/A');const debounce=(fn,wait=400)=>{let timer;return(...args)=>{clearTimeout(timer);timer=setTimeout(()=>fn(...args),wait)}};
function ratingClass(value){const text=String(value||'').toLowerCase();if(text.includes('excellent')||text.includes('exceptional')||text.includes('very high')||text.includes('inspiring')||text.startsWith('yes'))return'great';if(text.includes('good')||text==='high'||text.includes('perfect')||text.includes('comfortable'))return'good';if(text.includes('fair')||text.includes('average')||text.includes('moderate')||text.includes('maybe'))return'fair';return'poor'}
function badge(value){return`<span class="rating ${ratingClass(value)}">${display(value)}</span>`}
function render(data){pageData=data;const rows=data.data||[];document.getElementById('tableBody').innerHTML=rows.length?rows.map(item=>{const initials=(item.full_name||'?').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();return`<tr><td><div class="person"><div class="avatar">${escapeHtml(initials)}</div><div><div class="person-name">${display(item.full_name)}</div><div class="subtext">${display(item.email)}</div></div></div></td><td>${badge(item.rating_overall)}</td><td>${badge(item.spiritual_impact)}</td><td>${badge(item.content_quality)}</td><td>${badge(item.speaker_rating)}</td><td>${badge(item.attend_again)}</td><td class="text-end"><button class="action-btn" onclick="viewDetails(${item.id})" title="View full feedback"><i class="bi bi-eye"></i></button></td></tr>`}).join(''):'<tr><td colspan="7"><div class="empty"><i class="bi bi-chat-square-text fs-2 d-block mb-2"></i><strong>No feedback found</strong><div class="mt-1">Try changing the search or rating filter.</div></div></td></tr>';document.getElementById('resultSummary').textContent=`${data.total.toLocaleString()} result${data.total===1?'':'s'}`;document.getElementById('rangeText').textContent=data.total?`Showing ${data.from}–${data.to} of ${data.total}`:'No responses to show';renderPagination(data)}
function renderPagination(data){const list=document.getElementById('pagination');if(data.last_page<=1){list.innerHTML='';return}const pages=new Set([1,data.last_page,data.current_page-1,data.current_page,data.current_page+1]),visible=[...pages].filter(p=>p>=1&&p<=data.last_page).sort((a,b)=>a-b);let previous=0,html=`<li class="page-item ${data.current_page===1?'disabled':''}"><button class="page-link" data-page="${data.current_page-1}"><i class="bi bi-chevron-left"></i></button></li>`;visible.forEach(p=>{if(previous&&p-previous>1)html+='<li class="page-item disabled"><span class="page-link">…</span></li>';html+=`<li class="page-item ${p===data.current_page?'active':''}"><button class="page-link" data-page="${p}">${p}</button></li>`;previous=p});html+=`<li class="page-item ${data.current_page===data.last_page?'disabled':''}"><button class="page-link" data-page="${data.current_page+1}"><i class="bi bi-chevron-right"></i></button></li>`;list.innerHTML=html}
async function loadPage(page=1){if(requestController)requestController.abort();requestController=new AbortController();const params=new URLSearchParams({page}),search=document.getElementById('searchInput').value.trim(),rating=document.getElementById('ratingFilter').value;if(search)params.set('search',search);if(rating)params.set('rating',rating);document.getElementById('loading').style.display='grid';try{const response=await fetch(`${feedbackUrl}?${params}`,{headers:{Accept:'application/json','X-Requested-With':'XMLHttpRequest'},signal:requestController.signal});if(!response.ok)throw new Error('Could not load feedback');const payload=await response.json();render(payload.feedback);Object.entries(payload.stats).forEach(([key,value])=>{const el=document.querySelector(`[data-stat="${key}"]`);if(el)el.textContent=Number(value).toLocaleString()});history.replaceState({},'',`${feedbackUrl}?${params}`)}catch(error){if(error.name!=='AbortError')Swal.fire({icon:'error',title:'Unable to load feedback',text:error.message})}finally{document.getElementById('loading').style.display='none'}}
function viewDetails(id){const item=pageData.data.find(row=>row.id===id);if(!item)return;const fields=[['Full name',item.full_name],['Email',item.email],['Overall experience',item.rating_overall],['Spiritual impact',item.spiritual_impact],['Content quality',item.content_quality],['Speaker rating',item.speaker_rating],['Logistics',item.logistics],['Venue',item.venue_rating],['Attend again',item.attend_again],['Submitted',item.created_at?new Date(item.created_at).toLocaleString():'N/A']];const answers=[['Highlight sessions',item.highlight_sessions],['Suggested improvements',item.improvements],['Testimonies',item.testimonies]];document.getElementById('modalBody').innerHTML=`<div class="details-grid">${fields.map(([label,value])=>`<div class="detail"><label>${escapeHtml(label)}</label><div>${display(value)}</div></div>`).join('')}</div>${answers.map(([label,value])=>`<div class="long-answer"><label>${escapeHtml(label)}</label><p>${display(value)}</p></div>`).join('')}`;bootstrap.Modal.getOrCreateInstance(document.getElementById('detailsModal')).show()}
document.getElementById('searchInput').addEventListener('input',debounce(()=>loadPage(1)));document.getElementById('ratingFilter').addEventListener('change',()=>loadPage(1));document.getElementById('pagination').addEventListener('click',event=>{const button=event.target.closest('[data-page]');if(button&&!button.closest('.disabled')){loadPage(button.dataset.page);document.querySelector('.panel').scrollIntoView({behavior:'smooth',block:'start'})}});document.getElementById('exportBtn').addEventListener('click',()=>{const headers=['ID','Name','Email','Overall Rating','Spiritual Impact','Content Quality','Speaker Rating','Logistics','Venue','Attend Again','Highlights','Improvements','Testimonies'];const rows=pageData.data.map(item=>[item.id,item.full_name,item.email,item.rating_overall,item.spiritual_impact,item.content_quality,item.speaker_rating,item.logistics,item.venue_rating,item.attend_again,item.highlight_sessions,item.improvements,item.testimonies]);const csv=[headers,...rows].map(row=>row.map(cell=>`"${String(cell??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`conference-feedback-page-${pageData.current_page}.csv`;a.click();URL.revokeObjectURL(a.href)});render(pageData);
</script></body></html>
