<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Special Accommodation</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
    <style>
        :root{--ink:#172033;--muted:#718096;--brand:#5b5bd6;--line:#e7eaf0;--canvas:#f5f7fb}*{box-sizing:border-box}body{margin:0;background:var(--canvas);color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}.topbar{background:#fff;border-bottom:1px solid var(--line)}.page-shell{width:100%;padding:30px 24px 50px}.brand-mark{width:42px;height:42px;border-radius:13px;background:linear-gradient(135deg,var(--brand),#8b5cf6);display:grid;place-items:center;color:#fff}.subtext{font-size:.78rem;color:var(--muted)}.eyebrow{color:var(--brand);font-size:.73rem;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.page-title{font-weight:750;letter-spacing:-.035em}.panel{background:#fff;border:1px solid var(--line);border-radius:18px;box-shadow:0 10px 35px rgba(32,41,64,.05)}.form-control,.form-select{border-color:var(--line);border-radius:11px;min-height:44px}.form-control:focus,.form-select:focus{border-color:#aaaaf1;box-shadow:0 0 0 .2rem #5b5bd615}.btn-brand{background:var(--brand);border-color:var(--brand);color:#fff}.btn-brand:hover{background:#4848bf;color:#fff}.table{min-width:780px;margin:0}.table th{background:#fafbfc;color:#697386;font-size:.7rem;text-transform:uppercase;letter-spacing:.08em;padding:14px 18px}.table td{padding:15px 18px;vertical-align:middle;border-color:#eff1f5}.avatar{width:38px;height:38px;border-radius:11px;background:#ededff;color:var(--brand);display:grid;place-items:center;font-weight:800}.source-pill{background:#e8f8f1;color:#087d55;border-radius:999px;padding:5px 9px;font-size:.7rem;font-weight:700}.soft-btn{border:1px solid var(--line);background:#fff;color:var(--ink);border-radius:10px;padding:.55rem .8rem;font-weight:600}.pagination{margin:0}.page-link{border:0;color:#596274;border-radius:8px!important;margin:0 2px}.page-item.active .page-link{background:var(--brand)}
    </style>
</head>
<body>
<header class="topbar"><div class="container-fluid px-3 px-md-4 py-3 d-flex align-items-center justify-content-between"><div class="d-flex align-items-center gap-3"><div class="brand-mark"><i class="bi bi-stars"></i></div><div><div class="fw-bold">SPC Admin</div><div class="subtext">Special accommodation register</div></div></div><a href="{{ route('dashboard') }}" class="soft-btn text-decoration-none"><i class="bi bi-arrow-left me-2"></i>Registrations</a></div></header>

<main class="page-shell">
    <div class="d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3 mb-4"><div><div class="eyebrow mb-2">Accommodation planning</div><h1 class="page-title h2 mb-1">Special Accommodation</h1><p class="text-secondary mb-0">Enlist confirmed attendees and manage their contact details.</p></div><button class="btn btn-brand rounded-3 px-4 py-2" data-bs-toggle="modal" data-bs-target="#addModal"><i class="bi bi-person-plus-fill me-2"></i>Add person</button></div>

    @if(session('status'))<div class="alert alert-success alert-dismissible fade show"><i class="bi bi-check-circle-fill me-2"></i>{{ session('status') }}<button class="btn-close" data-bs-dismiss="alert"></button></div>@endif
    @if($errors->any())<div class="alert alert-danger"><strong>Please correct the following:</strong><ul class="mb-0 mt-1">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

    <section class="panel overflow-hidden">
        <div class="p-3 p-md-4 border-bottom d-flex flex-column flex-md-row gap-3 align-items-md-center justify-content-between">
            <form class="d-flex gap-2 flex-grow-1" method="GET"><input class="form-control" style="max-width:460px" name="search" value="{{ $search }}" placeholder="Search name, phone, departure or notes"><button class="btn btn-dark px-3"><i class="bi bi-search"></i></button>@if($search)<a class="btn btn-light" href="{{ route('special-accommodations.index') }}">Clear</a>@endif</form>
            <div class="subtext fw-semibold">{{ number_format($entries->total()) }} {{ Str::plural('person', $entries->total()) }}</div>
        </div>
        <div class="table-responsive"><table class="table"><thead><tr><th>Person</th><th>Phone</th><th>Possible departure</th><th>Notes</th><th>Added</th><th class="text-end">Actions</th></tr></thead><tbody>
            @forelse($entries as $entry)
                <tr><td><div class="d-flex align-items-center gap-2"><div class="avatar">{{ Str::upper(Str::substr($entry->name, 0, 1)) }}</div><div><div class="fw-bold">{{ $entry->name }}</div>@if($entry->registration)<span class="source-pill"><i class="bi bi-patch-check-fill me-1"></i>Confirmed registration</span>@else<span class="subtext">Manual entry</span>@endif</div></div></td><td><a href="tel:{{ $entry->phone }}" class="text-decoration-none">{{ $entry->phone }}</a></td><td><span class="small">{{ $entry->possible_departure_at?->format('M j, Y · g:i A') ?? 'Not specified' }}</span></td><td><span class="small">{{ $entry->notes ?: '—' }}</span></td><td><div class="small">{{ $entry->created_at->format('M j, Y') }}</div><div class="subtext">by {{ $entry->createdBy?->name ?? 'Deleted user' }}</div></td><td><div class="d-flex justify-content-end gap-2"><button class="btn btn-sm btn-outline-secondary edit-button" data-bs-toggle="modal" data-bs-target="#editModal" data-url="{{ route('special-accommodations.update', $entry) }}" data-name="{{ $entry->name }}" data-phone="{{ $entry->phone }}" data-departure="{{ $entry->possible_departure_at?->format('Y-m-d\\TH:i') }}" data-notes="{{ $entry->notes }}"><i class="bi bi-pencil"></i></button><form method="POST" action="{{ route('special-accommodations.destroy', $entry) }}" onsubmit="return confirm('Remove {{ addslashes($entry->name) }} from special accommodation?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></div></td></tr>
            @empty
                <tr><td colspan="6" class="text-center py-5 text-secondary"><i class="bi bi-people fs-2 d-block mb-2"></i><strong>No one enlisted yet.</strong><div class="small mt-1">Use “Add person” to select a confirmed registration.</div></td></tr>
            @endforelse
        </tbody></table></div>
        @if($entries->hasPages())<div class="p-3 border-top d-flex justify-content-between align-items-center"><span class="subtext">Showing {{ $entries->firstItem() }}–{{ $entries->lastItem() }} of {{ $entries->total() }}</span>{{ $entries->links('pagination::bootstrap-5') }}</div>@endif
    </section>
</main>

<div class="modal fade" id="addModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form class="modal-content border-0 rounded-4" method="POST" action="{{ route('special-accommodations.store') }}">@csrf<div class="modal-header"><div><div class="eyebrow">New entry</div><h5 class="modal-title mt-1">Add special accommodation</h5></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body">
    <label class="form-label fw-semibold">Search confirmed registrations</label><div class="position-relative mb-2"><i class="bi bi-search position-absolute text-secondary" style="left:14px;top:13px"></i><input type="search" class="form-control registration-search" style="padding-left:40px" placeholder="Type a name or phone number"></div><select class="form-select registration-picker" name="conference_registration_id"><option value="">Enter manually</option>@foreach($confirmedRegistrations as $registration)<option value="{{ $registration->id }}" data-name="{{ $registration->fullname }}" data-phone="{{ $registration->phone }}" @selected(old('conference_registration_id') == $registration->id)>{{ $registration->fullname }} — {{ $registration->phone }}</option>@endforeach</select><div class="subtext mt-1 registration-search-status">Start typing to quickly find an attendee. Selecting one fills the editable fields below.</div>
    <div class="row g-3 mt-1"><div class="col-12"><label class="form-label fw-semibold">Name</label><input class="form-control person-name" name="name" value="{{ old('name') }}" required></div><div class="col-12"><label class="form-label fw-semibold">Phone number</label><input class="form-control person-phone" name="phone" value="{{ old('phone') }}" required></div><div class="col-12"><label class="form-label fw-semibold">Possible time of departure <span class="text-secondary fw-normal">(optional)</span></label><input type="datetime-local" class="form-control" name="possible_departure_at" value="{{ old('possible_departure_at') }}"></div><div class="col-12"><label class="form-label fw-semibold">Notes <span class="text-secondary fw-normal">(optional)</span></label><textarea class="form-control" rows="3" name="notes">{{ old('notes') }}</textarea></div></div>
    </div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-brand">Add person</button></div></form></div></div>

<div class="modal fade" id="editModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form id="editForm" class="modal-content border-0 rounded-4" method="POST">@csrf @method('PATCH')<div class="modal-header"><h5 class="modal-title">Edit details</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="mb-3"><label class="form-label fw-semibold">Name</label><input class="form-control" name="name" required></div><div class="mb-3"><label class="form-label fw-semibold">Phone number</label><input class="form-control" name="phone" required></div><div class="mb-3"><label class="form-label fw-semibold">Possible time of departure</label><input type="datetime-local" class="form-control" name="possible_departure_at"></div><div><label class="form-label fw-semibold">Notes</label><textarea class="form-control" rows="3" name="notes"></textarea></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-brand">Save changes</button></div></form></div></div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script>
document.querySelectorAll('.registration-picker').forEach(select=>select.addEventListener('change',()=>{const option=select.selectedOptions[0],form=select.closest('form');if(!option.value)return;form.querySelector('.person-name').value=option.dataset.name||'';form.querySelector('.person-phone').value=option.dataset.phone||'';}));
document.querySelectorAll('.registration-search').forEach(input=>input.addEventListener('input',()=>{const form=input.closest('form'),select=form.querySelector('.registration-picker'),status=form.querySelector('.registration-search-status'),term=input.value.trim().toLowerCase();let matches=0;Array.from(select.options).forEach((option,index)=>{if(index===0)return;const matchesTerm=!term||`${option.dataset.name||''} ${option.dataset.phone||''}`.toLowerCase().includes(term);option.hidden=!matchesTerm;if(matchesTerm)matches++;});if(select.selectedOptions[0]?.hidden){select.value='';}status.textContent=term?`${matches} confirmed registration${matches===1?'':'s'} found.`:'Start typing to quickly find an attendee. Selecting one fills the editable fields below.';}));
document.querySelectorAll('.edit-button').forEach(button=>button.addEventListener('click',()=>{const form=document.getElementById('editForm');form.action=button.dataset.url;form.elements.name.value=button.dataset.name;form.elements.phone.value=button.dataset.phone;form.elements.possible_departure_at.value=button.dataset.departure||'';form.elements.notes.value=button.dataset.notes||'';}));
@if($errors->any()) bootstrap.Modal.getOrCreateInstance(document.getElementById('addModal')).show(); @endif
</script>
</body></html>
