<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Special Accommodation</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
    <style>
        :root{--ink:#172033;--muted:#718096;--brand:#5b5bd6;--line:#e7eaf0;--canvas:#f5f7fb}*{box-sizing:border-box}body{margin:0;background:var(--canvas);color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}.topbar{background:#fff;border-bottom:1px solid var(--line)}.page-shell{width:100%;padding:30px 24px 50px}.brand-mark{width:42px;height:42px;border-radius:13px;background:linear-gradient(135deg,var(--brand),#8b5cf6);display:grid;place-items:center;color:#fff}.subtext{font-size:.78rem;color:var(--muted)}.eyebrow{color:var(--brand);font-size:.73rem;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.page-title{font-weight:750;letter-spacing:-.035em}.panel{position:relative;background:#fff;border:1px solid var(--line);border-radius:18px;box-shadow:0 10px 35px rgba(32,41,64,.05)}.form-control,.form-select{border-color:var(--line);border-radius:11px;min-height:44px}.form-control:focus,.form-select:focus{border-color:#aaaaf1;box-shadow:0 0 0 .2rem #5b5bd615}.btn-brand{background:var(--brand);border-color:var(--brand);color:#fff}.btn-brand:hover{background:#4848bf;color:#fff}.table{min-width:780px;margin:0}.table th{background:#fafbfc;color:#697386;font-size:.7rem;text-transform:uppercase;letter-spacing:.08em;padding:14px 18px}.table td{padding:15px 18px;vertical-align:middle;border-color:#eff1f5}.avatar{width:38px;height:38px;border-radius:11px;background:#ededff;color:var(--brand);display:grid;place-items:center;font-weight:800}.source-pill{background:#e8f8f1;color:#087d55;border-radius:999px;padding:5px 9px;font-size:.7rem;font-weight:700}.soft-btn{border:1px solid var(--line);background:#fff;color:var(--ink);border-radius:10px;padding:.55rem .8rem;font-weight:600}.pagination{margin:0}.page-link{border:0;color:#596274;border-radius:8px!important;margin:0 2px}.page-item.active .page-link{background:var(--brand)}.registration-search-wrap{position:relative}.registration-results{position:absolute;z-index:1100;left:0;right:0;top:50px;background:#fff;border:1px solid var(--line);border-radius:13px;box-shadow:0 18px 45px rgba(32,41,64,.18);max-height:310px;overflow:auto}.registration-result{display:flex;width:100%;align-items:center;gap:11px;padding:12px 14px;border:0;border-bottom:1px solid #eff1f5;background:#fff;text-align:left}.registration-result:hover,.registration-result:focus{background:#f6f6ff}.result-icon{width:35px;height:35px;display:grid;place-items:center;border-radius:10px;background:#ededff;color:var(--brand);flex:none}.selected-registration{background:#f0fbf6;border:1px solid #bce7d4;border-radius:11px;padding:10px 12px}.panel-loading{position:absolute;inset:0;background:#ffffffc7;z-index:10;display:grid;place-items:center}.toast-box{position:fixed;top:18px;right:18px;z-index:2000;max-width:min(390px,calc(100vw - 36px))}
    </style>
</head>
<body>
<header class="topbar"><div class="container-fluid px-3 px-md-4 py-3 d-flex align-items-center justify-content-between"><div class="d-flex align-items-center gap-3"><div class="brand-mark"><i class="bi bi-stars"></i></div><div><div class="fw-bold">SPC Admin</div><div class="subtext">Special accommodation register</div></div></div><a href="{{ route('dashboard') }}" class="soft-btn text-decoration-none"><i class="bi bi-arrow-left me-2"></i>Registrations</a></div></header>

<main class="page-shell">
    <div class="d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3 mb-4"><div><div class="eyebrow mb-2">Accommodation planning</div><h1 class="page-title h2 mb-1">Special Accommodation</h1><p class="text-secondary mb-0">Enlist confirmed attendees and manage their contact details.</p></div><button class="btn btn-brand rounded-3 px-4 py-2" data-bs-toggle="modal" data-bs-target="#addModal"><i class="bi bi-person-plus-fill me-2"></i>Add person</button></div>

    @if(session('status'))<div class="alert alert-success alert-dismissible fade show"><i class="bi bi-check-circle-fill me-2"></i>{{ session('status') }}<button class="btn-close" data-bs-dismiss="alert"></button></div>@endif
    @if($errors->any())<div class="alert alert-danger"><strong>Please correct the following:</strong><ul class="mb-0 mt-1">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

    <section class="panel overflow-hidden" id="registerPanel">
        <div class="p-3 p-md-4 border-bottom d-flex flex-column flex-md-row gap-3 align-items-md-center justify-content-between">
            <form class="d-flex gap-2 flex-grow-1" method="GET" id="registerSearchForm"><input class="form-control" style="max-width:460px" name="search" value="{{ $search }}" autocomplete="off" placeholder="Search name, phone, departure or notes"><button class="btn btn-dark px-3"><i class="bi bi-search"></i></button>@if($search)<a class="btn btn-light clear-search" href="{{ route('special-accommodations.index') }}">Clear</a>@endif</form>
            <div class="subtext fw-semibold">{{ number_format($entries->total()) }} {{ Str::plural('person', $entries->total()) }}</div>
        </div>
        <div class="table-responsive"><table class="table"><thead><tr><th>Person</th><th>Phone</th><th>Possible departure</th><th>Notes</th><th>Added</th><th class="text-end">Actions</th></tr></thead><tbody>
            @forelse($entries as $entry)
                <tr><td><div class="d-flex align-items-center gap-2"><div class="avatar">{{ Str::upper(Str::substr($entry->name, 0, 1)) }}</div><div><div class="fw-bold">{{ $entry->name }}</div>@if($entry->registration)<span class="source-pill"><i class="bi bi-patch-check-fill me-1"></i>Confirmed registration</span>@else<span class="subtext">Manual entry</span>@endif</div></div></td><td><a href="tel:{{ $entry->phone }}" class="text-decoration-none">{{ $entry->phone }}</a></td><td><span class="small">{{ $entry->possible_departure_at?->format('M j, Y · g:i A') ?? 'Not specified' }}</span></td><td><span class="small">{{ $entry->notes ?: '—' }}</span></td><td><div class="small">{{ $entry->created_at->format('M j, Y') }}</div><div class="subtext">by {{ $entry->createdBy?->name ?? 'Deleted user' }}</div></td><td><div class="d-flex justify-content-end gap-2"><button class="btn btn-sm btn-outline-secondary edit-button" data-bs-toggle="modal" data-bs-target="#editModal" data-url="{{ route('special-accommodations.update', $entry) }}" data-name="{{ $entry->name }}" data-phone="{{ $entry->phone }}" data-departure="{{ $entry->possible_departure_at?->format('Y-m-d\\TH:i') }}" data-notes="{{ $entry->notes }}"><i class="bi bi-pencil"></i></button><form class="delete-form" method="POST" action="{{ route('special-accommodations.destroy', $entry) }}" data-name="{{ $entry->name }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></div></td></tr>
            @empty
                <tr><td colspan="6" class="text-center py-5 text-secondary"><i class="bi bi-people fs-2 d-block mb-2"></i><strong>No one enlisted yet.</strong><div class="small mt-1">Use “Add person” to select a confirmed registration.</div></td></tr>
            @endforelse
        </tbody></table></div>
        @if($entries->hasPages())<div class="p-3 border-top d-flex justify-content-between align-items-center"><span class="subtext">Showing {{ $entries->firstItem() }}–{{ $entries->lastItem() }} of {{ $entries->total() }}</span>{{ $entries->links('pagination::bootstrap-5') }}</div>@endif
    </section>
</main>

<div class="modal fade" id="addModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form id="addForm" class="modal-content border-0 rounded-4" method="POST" action="{{ route('special-accommodations.store') }}">@csrf<div class="modal-header"><div><div class="eyebrow">New entry</div><h5 class="modal-title mt-1">Add special accommodation</h5></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body">
    <div class="alert alert-danger d-none form-error"></div><label class="form-label fw-semibold">Search confirmed registrations</label><div class="registration-search-wrap mb-2"><i class="bi bi-search position-absolute text-secondary" style="left:14px;top:13px"></i><input type="search" id="registrationSearch" class="form-control" style="padding-left:40px" autocomplete="off" placeholder="Type at least 2 letters or phone digits"><div id="registrationResults" class="registration-results d-none"></div></div><input type="hidden" name="conference_registration_id" id="registrationId"><div id="selectedRegistration" class="selected-registration d-none mb-2"></div><div class="subtext">Choose a suggested attendee to autofill their details, or enter the details manually below.</div>
    <div class="row g-3 mt-1"><div class="col-12"><label class="form-label fw-semibold">Name</label><input class="form-control person-name" name="name" value="{{ old('name') }}" required></div><div class="col-12"><label class="form-label fw-semibold">Phone number</label><input class="form-control person-phone" name="phone" value="{{ old('phone') }}" required></div><div class="col-12"><label class="form-label fw-semibold">Possible time of departure <span class="text-secondary fw-normal">(optional)</span></label><input type="datetime-local" class="form-control" name="possible_departure_at" value="{{ old('possible_departure_at') }}"></div><div class="col-12"><label class="form-label fw-semibold">Notes <span class="text-secondary fw-normal">(optional)</span></label><textarea class="form-control" rows="3" name="notes">{{ old('notes') }}</textarea></div></div>
    </div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-brand submit-button">Add person</button></div></form></div></div>

<div class="modal fade" id="editModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form id="editForm" class="modal-content border-0 rounded-4" method="POST">@csrf @method('PATCH')<div class="modal-header"><h5 class="modal-title">Edit details</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="alert alert-danger d-none form-error"></div><div class="mb-3"><label class="form-label fw-semibold">Name</label><input class="form-control" name="name" required></div><div class="mb-3"><label class="form-label fw-semibold">Phone number</label><input class="form-control" name="phone" required></div><div class="mb-3"><label class="form-label fw-semibold">Possible time of departure</label><input type="datetime-local" class="form-control" name="possible_departure_at"></div><div><label class="form-label fw-semibold">Notes</label><textarea class="form-control" rows="3" name="notes"></textarea></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-brand submit-button">Save changes</button></div></form></div></div>

<div id="toastBox" class="toast-box"></div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script>
const indexUrl=@json(route('special-accommodations.index')), registrationSearchUrl=@json(route('special-accommodations.registration-search')), csrf=document.querySelector('meta[name="csrf-token"]').content;
const addModal=bootstrap.Modal.getOrCreateInstance('#addModal'), editModal=bootstrap.Modal.getOrCreateInstance('#editModal');
let registrationTimer, listTimer, searchController, listController;
const escapeHtml=value=>{const element=document.createElement('div');element.textContent=value??'';return element.innerHTML};

async function request(url,options={}){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(url,{...options,signal:options.signal||controller.signal,headers:{Accept:'application/json','X-Requested-With':'XMLHttpRequest',...(options.headers||{})}}),type=response.headers.get('content-type')||'',payload=type.includes('application/json')?await response.json():await response.text();if(!response.ok){const error=new Error(typeof payload==='object'?(Object.values(payload.errors||{}).flat()[0]||payload.message):'The server returned an unexpected response.');error.validation=response.status===422;throw error}return payload}catch(error){if(error.name==='AbortError')throw new Error('The request timed out. Please try again.');if(error instanceof TypeError)throw new Error('No network connection. Check your internet and try again.');throw error}finally{clearTimeout(timeout)}}
function toast(message,type='success'){document.getElementById('toastBox').innerHTML=`<div class="alert alert-${type} shadow-lg border-0 alert-dismissible fade show"><i class="bi bi-${type==='success'?'check-circle-fill':'exclamation-triangle-fill'} me-2"></i>${escapeHtml(message)}<button class="btn-close" data-bs-dismiss="alert"></button></div>`}
function setLoading(loading){const panel=document.getElementById('registerPanel');panel.querySelector('.panel-loading')?.remove();if(loading)panel.insertAdjacentHTML('beforeend','<div class="panel-loading"><div class="spinner-border text-primary"></div></div>')}
async function refreshList(url=location.href,push=true){listController?.abort();listController=new AbortController();setLoading(true);try{const response=await fetch(url,{headers:{'X-Requested-With':'XMLHttpRequest'},signal:listController.signal});if(!response.ok)throw new Error('Could not refresh the accommodation register.');const html=await response.text(),documentCopy=new DOMParser().parseFromString(html,'text/html'),panel=documentCopy.getElementById('registerPanel');if(!panel)throw new Error('The server returned an invalid page.');document.getElementById('registerPanel').replaceWith(panel);if(push)history.replaceState({},'',url)}catch(error){if(error.name!=='AbortError')toast(error.message,'danger')}finally{setLoading(false)}}

document.getElementById('registrationSearch').addEventListener('input',event=>{clearTimeout(registrationTimer);searchController?.abort();const term=event.target.value.trim(),results=document.getElementById('registrationResults');document.getElementById('registrationId').value='';document.getElementById('selectedRegistration').classList.add('d-none');if(term.length<2){results.classList.add('d-none');results.innerHTML='';return}results.classList.remove('d-none');results.innerHTML='<div class="text-center py-3"><span class="spinner-border spinner-border-sm text-primary"></span></div>';registrationTimer=setTimeout(async()=>{searchController=new AbortController();try{const payload=await request(`${registrationSearchUrl}?q=${encodeURIComponent(term)}`,{signal:searchController.signal});results.innerHTML=payload.results.length?payload.results.map(person=>`<button type="button" class="registration-result" data-id="${person.id}" data-name="${escapeHtml(person.fullname)}" data-phone="${escapeHtml(person.phone)}"><span class="result-icon"><i class="bi bi-person-check-fill"></i></span><span><strong class="d-block">${escapeHtml(person.fullname)}</strong><span class="subtext"><i class="bi bi-telephone me-1"></i>${escapeHtml(person.phone||'No phone')}</span></span></button>`).join(''):'<div class="text-center text-secondary py-4"><i class="bi bi-search d-block mb-1"></i>No available confirmed registration found.</div>'}catch(error){if(error.name!=='AbortError')results.innerHTML=`<div class="text-center text-danger py-3">${escapeHtml(error.message)}</div>`}},250)});
document.getElementById('registrationResults').addEventListener('click',event=>{const result=event.target.closest('.registration-result');if(!result)return;const form=document.getElementById('addForm');form.elements.conference_registration_id.value=result.dataset.id;form.elements.name.value=result.dataset.name;form.elements.phone.value=result.dataset.phone;document.getElementById('registrationSearch').value=result.dataset.name;document.getElementById('registrationResults').classList.add('d-none');const selected=document.getElementById('selectedRegistration');selected.innerHTML=`<i class="bi bi-patch-check-fill text-success me-2"></i><strong>${escapeHtml(result.dataset.name)}</strong><span class="subtext ms-2">${escapeHtml(result.dataset.phone)}</span>`;selected.classList.remove('d-none')});

document.addEventListener('submit',async event=>{if(event.target.id==='registerSearchForm'){event.preventDefault();const params=new URLSearchParams(new FormData(event.target));await refreshList(`${indexUrl}?${params}`);return}if(!event.target.matches('#addForm,#editForm,.delete-form'))return;event.preventDefault();const form=event.target,isDelete=form.classList.contains('delete-form');if(isDelete&&!confirm(`Remove ${form.dataset.name} from special accommodation?`))return;const button=form.querySelector('button[type="submit"],button:not([type])'),error=form.querySelector('.form-error'),data=new FormData(form);if(error)error.classList.add('d-none');if(button){button.disabled=true;button.dataset.label=button.innerHTML;button.innerHTML='<span class="spinner-border spinner-border-sm me-2"></span>Saving…'}try{const payload=await request(form.action,{method:'POST',headers:{'X-CSRF-TOKEN':csrf},body:data});if(form.id==='addForm'){addModal.hide();form.reset();document.getElementById('selectedRegistration').classList.add('d-none')}if(form.id==='editForm')editModal.hide();await refreshList(location.href,false);toast(payload.message)}catch(exception){if(error&&exception.validation){error.textContent=exception.message;error.classList.remove('d-none')}else toast(exception.message,'danger')}finally{if(button){button.disabled=false;button.innerHTML=button.dataset.label}}});
document.addEventListener('click',event=>{const edit=event.target.closest('.edit-button');if(edit){const form=document.getElementById('editForm');form.action=edit.dataset.url;form.elements.name.value=edit.dataset.name;form.elements.phone.value=edit.dataset.phone;form.elements.possible_departure_at.value=edit.dataset.departure||'';form.elements.notes.value=edit.dataset.notes||'';form.querySelector('.form-error').classList.add('d-none');return}const page=event.target.closest('#registerPanel .pagination a');if(page){event.preventDefault();refreshList(page.href);return}const clear=event.target.closest('.clear-search');if(clear){event.preventDefault();refreshList(clear.href)}});
document.addEventListener('input',event=>{if(!event.target.matches('#registerSearchForm input[name="search"]'))return;clearTimeout(listTimer);listTimer=setTimeout(()=>{const params=new URLSearchParams(new FormData(event.target.form));refreshList(`${indexUrl}?${params}`)},350)});
document.addEventListener('click',event=>{if(!event.target.closest('.registration-search-wrap'))document.getElementById('registrationResults').classList.add('d-none')});
window.addEventListener('offline',()=>toast('You are offline. Changes cannot be saved.','danger'));window.addEventListener('online',()=>toast('Your connection is back.'));
</script>
</body></html>
